### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by IgorGanapolsky** [Dan1ve/MaterialTabsListScrolling#2]
Hi, can you please implement an example with multiple tabs in the Toolbar?  Something like Google Play app does.

Thanks a lot,
Igor

**Comment by Dan1ve** [comment]
Hi Igor,

I will if I find the time, but unfortunately my university and job keep 
me quite busy at the moment. ;)

In the meantime, I suggest you take a look at 
https://developer.android.com/samples/SlidingTabsBasic/src/com.example.android.common/view/SlidingTabLayout.html# 
and use the SlidingTabLayout & SlidingTabStrip views in your project 
like in the Android developer example.
There are a few customizations needed to make them fully Material, but 
it will perfectly work (I use them myself in my project).

The good news is: You can simply replace the dummy tab view from my 
github example with the working SlidingTabLayout and the scrolling 
toolbar bevahiour _should_ still work as before! ;-)

Hope that helps!
Best regards,
Daniel

Am 28.04.2015 um 18:25 schrieb Igor Ganapolsky:
