### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [Dan1ve/MaterialTabsListScrolling#3]
Can you please show how to do it all using the design library, and show how to use a ListView instead?

I've tried messing around with a similar repo (here: https://github.com/chrisbanes/cheesesquare ) , but I've found some icons issues for the tabs (here: http://stackoverflow.com/q/31828610/878126 ) and also I can't find out how to set the scrolling work for ListViews inside the fragments.

**Comment by Dan1ve** [comment]
Hi, I'll try to figure it out and update this repo/the medium post, but unfortunately, I cannot make any promises :wink:

**Comment by AndroidDeveloperLB** [comment]
wow this was a fast response. Thank you. 
Is it possible that I'd need to make the ListView implement NestedScrollingChild  or something?

**Comment by Dan1ve** [comment]
No problem :) 
That's a really good question - Maybe you can figure it out by looking at the RecyclerView source code?

Edit: PS: Why not use RecyclerView which works out of the box?

**Comment by AndroidDeveloperLB** [comment]
Hope to try it.

**Comment by AndroidDeveloperLB** [comment]
I think it would be easier to use RecyclerView instead, sadly.
